### ISSUE TITLE
no such file: 'commit0/repos/pyjwt/spec.pdf'

### ISSUE THREAD

**Issue by chenqianhe** [commit-0/commit0#71]
I see `spec.pdf.bz2`, seems to lack unzip

```
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenqianhe/PycharmProjects/venv/commit0/lib/python3.12/site-packages/agent/run_agent.py", line 132, in run_agent_for_repo
    message = get_message(agent_config, repo_path, test_file=test_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenqianhe/PycharmProjects/venv/commit0/lib/python3.12/site-packages/agent/agent_utils.py", line 255, in get_message
    + get_specification(specification_pdf_path=Path(repo_path, "spec.pdf"))[
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenqianhe/PycharmProjects/venv/commit0/lib/python3.12/site-packages/agent/agent_utils.py", line 271, in get_specification
    document = fitz.open(specification_pdf_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenqianhe/PycharmProjects/venv/commit0/lib/python3.12/site-packages/pymupdf/__init__.py", line 2777, in __init__
    raise FileNotFoundError(msg)
pymupdf.FileNotFoundError: no such file: '/Users/chenqianhe/PycharmProjects/commit0/repos/pyjwt/spec.pdf'
```

**Comment by wenting-zhao** [comment]
Hi! This is addressed in [72552d4e6b45974715d004ae72e4eb81ae12af83](https://github.com/commit-0/commit0/commit/72552d4e6b45974715d004ae72e4eb81ae12af83).

Please pull the latest main or run `pip install -U commit0`.

I tested with

```
agent config aider --use-spec-info
agent run fillin-spec
```

It seems to work fine for me. When I checked ``vim logs/agent/simpy/fillin-spec/2024-09-28_15-01-36/src__simpy__resources__resource/.aider.chat.history.md `` The spec information is included in the chat.

Let me know if you run into more errors!

**Comment by chenqianhe** [comment]
I can run it normally.

btw, `spec.pdf` is generated by you, why not save it in markdown or other formats that are easier for programs to read?
At the same time, can the content of `spec` be optimized, such as removing useless information(e.g. version update records)?

**Comment by wenting-zhao** [comment]
The point of saving specs in PDFs is because they has richer information such as figures. We believe that reading specs is a multi-modal problem. For example, an overview figure would help human software engineers to understand the overall structure of a repo. As another example, figures in seaborn also help with understanding how the end deliverable code should look like. We understand that this is very out of scope at the moment, but we are planning for the future.
