### ISSUE TITLE
Running specific agent configurations for SimPy split errors

### ISSUE THREAD

**Issue by EugeneChoi4** [commit-0/commit0#77]
There is an error right now when attempting to run an agent for the SimPy split on commit0 version 0.1.6. Error fails with:
`KeyError: 'src/simpy/core.py'`. Steps to reproduce are the following, after a clean reinstall of commit0:

- Create a simpy split using `commit0 setup simpy`
- Create an agent with `agent config --model-name gpt-4o-mini --use-repo-info --use-spec-info`. Note that only the repo info and spec info options are toggled. 
- Run the agent on the commit0 branch with `agent run commit0`

A screenshot of the error is shown below:
<img width="929" alt="Screen Shot 2024-10-22 at 5 05 32 PM" src="https://github.com/user-attachments/assets/f4772cf2-58dc-4eac-a33a-cc661c689e33">

For some reason, this error does not occur with more options toggled on.

**Comment by nanjiangwill** [comment]
fixed, will push soon

**Comment by EugeneChoi4** [comment]
Has this issue been fully fixed? I tried cloning this commit0 repository to manually generate the .whl file and install the latest commit0 CLI, however I run into a new error now when trying to run `agent run BRANCH` on the simpy split (with default agent settings)

<img width="1039" alt="Screen Shot 2024-10-25 at 3 47 06 PM" src="https://github.com/user-attachments/assets/6184ad7b-cabe-47c2-9a49-89301da263a5">
