### ISSUE TITLE
Aider agent error with linting setting on

### ISSUE THREAD

**Issue by EugeneChoi4** [commit-0/commit0#78]
It seems as though toggling the linting option (`use_lint_info: true`) causes the aider agent to run into errors when executing. This does not cause the program to crash; however the agent is not able to make any progress as a result. 

The following error was recreated with a SimPy split and the `use_lint_info: true` option:
<img width="823" alt="Screen Shot 2024-10-22 at 11 57 23 PM" src="https://github.com/user-attachments/assets/86184d07-ec36-4de3-9909-5081b10d2f2a">
.
.
.
<img width="938" alt="Screen Shot 2024-10-22 at 11 57 45 PM" src="https://github.com/user-attachments/assets/847466b6-1bf6-4318-9d12-7ebe80129cc9">

**Comment by nanjiangwill** [comment]
specifying `--commit0_dot_file_path` is required

fixed in `add-swebench` branch and will merge soon
