### ISSUE TITLE
setup bug

### ISSUE THREAD

**Issue by MaxWhitton25** [commit-0/commit0#80]
When cloning parsel, the 'setup' method is not included, which causes 196/206 of the tests to fail

**Comment by wenting-zhao** [comment]
is setup function part of the parsel library? if it is, then this is a bug that models need to fix, not a bug of commit0.

**Comment by EugeneChoi4** [comment]
The setup function is part of the original xpathfuncs.py file [here](https://github.com/commit-0/parsel/blob/master/parsel/xpathfuncs.py), however when we run `commit0 setup parsel` the function is just deleted, without any `pass` statements associated with it.

**Comment by wenting-zhao** [comment]
this is by design
