### ISSUE TITLE
Agent run command is not committing to a branch

### ISSUE THREAD

**Issue by EugeneChoi4** [commit-0/commit0#81]
After running the `agent run BRANCH command`, commits made by the aider agent are not associated with any particular branch, rather they leave the working repository in a detached HEAD state. I had to go manually move these commits to the desired `BRANCH` to then evaluate. A screenshot of the detached commits made by the aider agent is shown below:

![Screen Shot 2024-10-25 at 2 03 17 PM](https://github.com/user-attachments/assets/22723dc4-0050-44b9-8239-d3dd8e9ce924)

**Comment by wenting-zhao** [comment]
@nanjiangwill

**Comment by nanjiangwill** [comment]
could you send me your `agent.yaml`? please regenerate with latest agent cli, if error is still there, send me the `agent.yaml` and `commit0.yaml`

**Comment by EugeneChoi4** [comment]
This was indeed fixed with the latest commit0, thank you!
