### ISSUE TITLE
Follow-Up on issue #77

### ISSUE THREAD

**Issue by EugeneChoi4** [commit-0/commit0#83]
Has this issue been fully fixed? I tried cloning this commit0 repository to manually generate the .whl file and install the latest commit0 CLI, however I run into a new error now when trying to run `agent run BRANCH` on the simpy split (with default agent settings)

<img width="1039" alt="Screen Shot 2024-10-25 at 3 47 06 PM" src="https://github.com/user-attachments/assets/6184ad7b-cabe-47c2-9a49-89301da263a5">

_Originally posted by @EugeneChoi4 in https://github.com/commit-0/commit0/issues/77#issuecomment-2438673801_

**Comment by nanjiangwill** [comment]
you need to regenerate agent.yaml with `agent config` there are arguments updated

**Comment by wenting-zhao** [comment]
@EugeneChoi4 Please check back in with us to let us know if what Nan suggested help you resolve the issue

**Comment by EugeneChoi4** [comment]
It works! Thank you.
