### ISSUE TITLE
"commit0 evaluate" command error with branch, functional with --reference argument

### ISSUE THREAD

**Issue by denizbt** [commit-0/commit0#88]
We run the default aider agent on the simpy repository split, which commits its changes to a branch called `commit0-test`. However, when we then run the command `commit0 evaluate --branch commit0-test`, it does not seem that any of the unit test cases are evaluated. No error output is given to the terminal. However, in the logs/pytest/simpy/commit0-test/pytest_exit_code.txt directory, we are told that the PyTest error code is 4 ("pytest command line usage error" according to documentation). 

On the other hand, in the same repository, the command `commit0 evaluate --reference` runs without issue.

See the image for the terminal output for the two commands:
<img width="1400" alt="Screenshot 2024-10-28 at 01 34 10" src="https://github.com/user-attachments/assets/1256376f-1d63-4fda-b0ce-8d8dbd0ae1b7">

**Comment by wenting-zhao** [comment]
Confirmed with Deniz: the newest version doesn't have this issue anymore.
